config/routes.rb
Rails.application.routes.draw do
  root 'advertisements#index'
  resources :advertisements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :advertisement
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  has_one :address
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  include Trailblazer::Endpoint::Controller

  def index
    @advertisements = Advertisement.all
  end

  def new
    @advertisement ||= Advertisement.new(address: Address.new)
  end

  def create
    verified_params = params[:advertisement].permit(:title, :description, :price, address: [:formatted_address, :lat, :lon])
    endpoint_app ::Advertisement::Create, args: [verified_params] do |m|
      m.success do
        flash[:notice] = 'Created successful'
        redirect_to root_path
      end
      m.invalid do |result|
        @advertisement = result['model']
        @errors = result['result.contract.default'].errors
        respond_to do |format|
          format.html { render :new }
        end
      end
    end
  end
end

app/controllers/application_controller.rb
require 'trailblazer/endpoint/rails'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def endpoint_app(operation_class, options={}, &block)
    endpoint operation_class, options do |m|
      if block
        block.call(m)
      end
      m.not_found {}
      m.unauthenticated {}
      m.present {}
      m.created {}
      m.success {}
      m.invalid {}
    end
  end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advertisement/index.html.haml
%h3
- if @advertisements.empty?
  .row
    .column.small-4
      &nbsp;
    .column.small-4
      = image_tag 'pure_cat.jpg', { width: 400 }
      .text-center.gray
        Nothing found
    .column.small-4
      &nbsp;
- else
  - @advertisements.each do |adv|
    .media-object.stack-for-small
      .media-object-section
        %img.thumbnail(src="https://dummyimage.com/100x100/878787/525252.png&text=No+image")
      .media-object-section
        %h5=adv.title
        %p=adv.description

app/views/advertisement/new.html.haml
%h3
  = I18n.t('New advertisement')
%p.gray
  Please adds your advertisement
= form_for @advertisement, url: { action: :create } do |f|
  .row
    .column
      = f.label :title
    .column
      = f.text_field :title
  .row
    .column
      = f.label :description
    .column
      = f.text_area :description, rows: 10
  .row
    .column
      = f.label :price
    .column
      = f.text_field :price
  .row
    .column
      = f.submit I18n.t("send"), class: 'button'

app/views/advertisements/index.html.haml
- if flash[:notice]
  .notice
    = flash[:notice]


- if @advertisements.empty?
  .row
    .column.small-4
      &nbsp;
    .column.small-4
      = image_tag 'pure_cat.jpg', { width: 400 }
      .text-center.gray
        Nothing found
    .column.small-4
      &nbsp;
- else
  - @advertisements.each do |adv|
    .media-object.stack-for-small
      .media-object-section
        %img.thumbnail(src="https://dummyimage.com/100x100/878787/525252.png&text=No+image")
      .media-object-section
        %h5=adv.title
        %p=adv.description
        %p=adv.address.try(:formatted_address)

app/views/advertisements/new.html.haml
.div(ng-controller="AdvertisementNewController")
  .header
    %h3.title
      = I18n.t('New advertisement')
    %p.announcement
      Please adds your advertisement

  .form
    - if @errors && @errors.any?
      .form_errors
        %div.errors_overview
          %span.title
            = "#{pluralize(@errors.count, "error")} prohibited this task from being saved:"
          %ul.items
            - @errors.full_messages.each do |msg|
              %li
                = msg

    = form_for @advertisement, html: { class: 'form_fields', name: 'myForm' } do |f|
      = f.fields_for :address do |ff|
        .row.field_group
          .column
            Address
          .column
            = ff.text_field :formatted_address, id: 'addresspicker', class: 'text_field', 'ng-model': 'ad.address.formatted_address', 'ng-init': "ad.address.formatted_address='#{@advertisement.address.formatted_address}'", required: ''
            -#%span
            = ff.hidden_field :lat, value: '{{ad.address.lat}}', 'ng-init': "ad.address.lat='#{@advertisement.address.lat}'"
            = ff.hidden_field :lon, value: '{{ad.address.lon}}', 'ng-init': "ad.address.lon='#{@advertisement.address.lon}'"

      .row.field_group
        .column
          = f.label :title
        .column
          = f.text_field :title, 'ng-model': 'ad.title', class: 'text_field', 'ng-init': "ad.title='#{@advertisement.title}'", required: '', maxlength: '{{title_max_number_letters}}', trim: ''
          .hint
            Max number words {{title_max_number_letters - ad.title.length}}

      .row.field_group
        .column
          = f.label :description
        .column
          = f.text_area :description, rows: 10, 'ng-model': 'ad.description', 'ng-init': "ad.description='#{@advertisement.description}'", required: '', trim: ''
      .row.field_group
        .column
          = f.label :price
        .column.small-2
          = f.number_field :price, value: 0, 'ng-model': 'ad.price', 'ng-init': "ad.price=#{@advertisement.price}", class: 'text_field--number', min: 1, required: ''
        .column.small-10.post_inform
          ₽

      .row.field_group.form_buttons
        .column
          = f.submit I18n.t("send"), class: 'button'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= csrf_meta_tags %>
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
</head>

<body ng-app="app" class="page">
<!-- Start Top Bar -->
<div class="top-bar">
  <div class="row">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Advertisement board</li>
        <li class="has-submenu">
          <!--<a href="#">One</a>-->
          <!--<ul class="submenu menu vertical" data-submenu>-->
            <!--<li><a href="#">One</a></li>-->
            <!--<li><a href="#">Two</a></li>-->
            <!--<li><a href="#">Three</a></li>-->
          <!--</ul>-->
        <!--</li>-->
        <!--<li><a href="#">Two</a></li>-->
        <!--<li><a href="#">Three</a></li>-->
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li>
          <%= link_to "+ Add advertisement", new_advertisement_path(), class: 'button' %>
          <!--<%= button_tag "+ Add advertisement" %>-->
          <!--<button type="button" class="button">+ sAdd advertisement</button>-->
        </li>
      </ul>
    </div>
  </div>
</div>
<br/>
<!-- End Top Bar -->
<div class="row columns">
  <!--<nav aria-label="You are here:" role="navigation">-->
    <!--<ul class="breadcrumbs">-->
      <!--<li><a href="#">Home</a></li>-->
      <!--<li><a href="#">Features</a></li>-->
      <!--<li class="disabled">Gene Splicing</li>-->
      <!--<li>-->
        <!--<span class="show-for-sr">Current: </span> Cloning-->
      <!--</li>-->
    <!--</ul>-->
  <!--</nav>-->
</div>
<div class="row main_content">
  <div class="column">
    <%= yield %>
  </div>
</div>

<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
<script>
  $(document).foundation();
</script>
</body>
</html>